'use client'

import { createContext, useContext, useState, useEffect, ReactNode } from 'react'

type Lang = 'zh' | 'en'

const translations = {
  zh: {
    appName: 'TasteDNA',
    editorTitle: '设计规范编辑器',
    saving: '保存中…',
    saved: '已自动保存',
    copyPrompt: '复制 AI Prompt',
    share: '分享',
    copied: '✓ 链接已复制',
    editorPlaceholder: '在左侧输入 DESIGN.md 内容…',
    previewPlaceholder: '在左侧粘贴 DESIGN.md 内容，这里会实时渲染可视化预览',
    previewFooter: '由 TasteDNA 生成 · 基于 DESIGN.md 规范',
    pickColor: '选色',
    download: '下载 DESIGN.md',
  },
  en: {
    appName: 'TasteDNA',
    editorTitle: 'Design Spec Editor',
    saving: 'Saving…',
    saved: 'Auto-saved',
    copyPrompt: 'Copy AI Prompt',
    share: 'Share',
    copied: '✓ Link copied',
    editorPlaceholder: 'Type DESIGN.md content on the left…',
    previewPlaceholder: 'Paste DESIGN.md content on the left to see the live visual preview',
    previewFooter: 'Generated by TasteDNA · Powered by DESIGN.md',
    pickColor: 'Pick color',
    download: 'Download DESIGN.md',
  },
} as const

type TranslationKey = keyof typeof translations.zh

const LanguageContext = createContext<{
  lang: Lang
  setLang: (l: Lang) => void
  t: (key: TranslationKey) => string
}>({
  lang: 'zh',
  setLang: () => {},
  t: (key) => translations.zh[key],
})

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Lang>('zh')

  useEffect(() => {
    const saved = localStorage.getItem('tastedna-lang') as Lang | null
    if (saved === 'en' || saved === 'zh') setLangState(saved)
  }, [])

  const setLang = (l: Lang) => {
    setLangState(l)
    localStorage.setItem('tastedna-lang', l)
  }

  const t = (key: TranslationKey) => translations[lang][key]

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  return useContext(LanguageContext)
}
